######################################################################
# Automatically generated by qmake (3.0) Mon Feb 17 12:56:51 2014
######################################################################

TEMPLATE = app
TARGET = reduce
INCLUDEPATH += .
QMAKE_CXXFLAGS += -g -pg -fno-inline
QMAKE_LFLAGS += -g -pg
# Input
SOURCES += mainCPU.cpp
